apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-latest
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  sourceRef:
    kind: DataSource
    name: fedora
    namespace: openshift-virtualization-os-images
  storage:
    resources:
      requests:
        storage: 30Gi
    volumeMode: Filesystem