apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  name: fedora-latest
spec:
  source:
    registry:
      url: docker://quay.io/ch007m/quarkus-dev-vm #docker://quay.io/containerdisks/fedora
  storage:
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
