apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-cloud-39-base
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    registry:
      url: "docker://quay.io/ch007m/fedora:39"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 9Gi
    volumeMode: Filesystem