apiVersion: v1
kind: Service
metadata:
  name: fedora38-loadbalancer-ssh-service
spec:
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
  selector:
    kubevirt.io/domain: fedora38
  sessionAffinity: None
  type: LoadBalancer