apiVersion: v1
kind: Service
metadata:
  name: fedora38-service
  namespace: development
spec:
  externalIPs:
    - 10.0.213.1
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32175
      port: 22000
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/domain: fedora38
  sessionAffinity: None
  type: NodePort
