apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: quarkus-maven-build
spec:
  pipelineRef:
    name: quarkus-maven-build
  params:
    - name: debug
      value: "false"
    - name: deploy
      value: "true"
    - name: url
      value: "https://github.com/iocanel/quarkus-helloworld"
    - name: virtualMachineName
      value: "quarkus-dev"
  workspaces:
    - name: project-dir
      persistentVolumeClaim:
        claimName: project-pvc
    - name: maven-m2-repo
      persistentVolumeClaim:
        claimName: m2-repo-pvc
    - name: maven-settings
      configMap:
        name: maven-settings
    - name: dockerconfig-ws
      secret:
        secretName: dockerconfig-secret
