#
# PipelineRun used for GitHub Actions
# As we build using Quarkus JIB ad push the image to Quay, this
# is why we create a workspace using the secret dockerconfig-secret
# packaging the Quay credentials
# The project cloned uses as quarkus extension kubernetes and not openshift
# to generate the resiurces and deploy them to the cluster
#
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: quarkus-maven-build
spec:
  pipelineRef:
    name: quarkus-maven-build
  params:
    - name: debug
      value: "false"
    - name: deploy
      value: "true"
    - name: url
      value: "https://github.com/ch007m/quarkus-helloworld"
    - name: virtualMachineName
      value: "quarkus-dev"
  workspaces:
    - name: project-dir
      persistentVolumeClaim:
        claimName: project-pvc
    - name: maven-m2-repo
      persistentVolumeClaim:
        claimName: m2-repo-pvc
    - name: maven-settings
      configMap:
        name: maven-settings
    - name: dockerconfig-ws
      secret:
        secretName: dockerconfig-secret
