apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: project-dir
      description: A workspace for the task
      optional: true
      mountPath: /mnt/workspace
  steps:
    - name: clone
      image: quay.io/redhat-cop/ubi8-git:v1.0
      workingDir: $(workspaces.project-dir.path)
      command:
        - sh
        - -c
      args:
        - git clone https://github.com/iocanel/quarkus-helloworld.git .
