apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vm-ip
spec:
  params:
    - name: vmName
      description: Name of the VirtualMachine to look for
      type: string
      default: "fedora37"
  results:
    - name: vm-ip
      description: IP address of the VM
  steps:
    - name: get-vm-ip
      image: quay.io/ch007m/kubectl-jq
      env:
        - name: PARAM_VM_NAME
          value: $(params.vmName)
      args:
        - "--env-vars"
      script: |
        #!/usr/bin/env bash
        set -eu
        
        VM_IP=$(kubectl get vmi/${PARAM_VM_NAME} -ojson | jq -r '.status.interfaces[] | .ipAddress')
        echo -n "$VM_IP"  | tee "$(results.vm-ip.path)"
