apiVersion: v1
kind: Service
metadata:
  name: quarkus-dev-http-service
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    kubevirt.io/domain: quarkus-dev
  sessionAffinity: None
  type: LoadBalancer