apiVersion: v1
kind: Service
metadata:
  name: quarkus-dev-loadbalancer-ssh-service
spec:
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
  selector:
    kubevirt.io/domain: quarkus-dev
  sessionAffinity: None
  type: LoadBalancer