apiVersion: v1
kind: Service
metadata:
  name: fedora38-http-service
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    kubevirt.io/domain: fedora38
  sessionAffinity: None
  type: LoadBalancer