apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
  namespace: test3
spec:
  source:
    pvc:
      namespace: openshift-virtualization-os-images
      name: fedora-498bd939ff7a
  pvc:
    accessModes:
      - ReadOnlyMany
    resources:
      requests:
        storage: 32Gi