apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - quarkus-maven-build.yaml

patches:
  - patch: |
      - op: replace #action
        path: /spec/tasks/6/params/1/value # !! Index must be hard coded
        value:
        - quarkus:deploy
        - -B
        - -Dquarkus.kubernetes.build-strategy=docker
        - -Dquarkus.kubernetes.deploy=false
        - -Dquarkus.container-image.build=true
        - -Dquarkus.log.level=DEBUG
    target:
      group: tekton.dev
      version: v1
      kind: Pipeline