apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-maven-build
spec:
  params:
    - name: url
      type: string
      description: url of the git repository to clone
    - name: virtualMachineName
      type: string
      description: name of the virtual machine to use
    - description: A boolean indicating whether we would like to execute a task
      default: "false"
      name: debug
      type: string
  workspaces:
    - name: project-dir
    - name: maven-settings
  tasks:
    - name: rm-workspace
      taskRef:
        name: rm-workspace
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: git-clone
      runAfter:
        - rm-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: ls-workspace
      runAfter:
        - git-clone
      taskRef:
        name: ls-workspace
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: virtualmachine
      runAfter:
        - ls-workspace
      taskRef:
        name: virtualmachine
      params:
        - name: name
          value: $(params.virtualMachineName)

    - name: create-remote-container
      runAfter:
        - virtualmachine
      when:
        - input: $(params.debug)
          operator: in
          values: [ "true" ]
      params:
        - name: dockerHost
          value: $(tasks.virtualmachine.results.ip)"
      taskSpec:
        params:
          - name: dockerHost
            description: docker host to use
            type: string
        steps:
          - name: create-container
            image: ghcr.io/ch007m/podman-client
            script: |
              #!/usr/bin/env bash
              
              echo "Getting podman information for host: $(params.dockerHost)"
              REMOTE_PARAMS="-r --url=tcp://$(params.dockerHost):2376"

              podman -r --url=tcp://10.128.2.169:2376 run -i --name my-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 postgres

    - name: maven
      runAfter:
        - virtualmachineqq
      taskRef:
        name: maven
      params:
        - name: DOCKER_HOST
          value: "tcp://$(tasks.virtualmachine.results.ip):2376"
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: project-dir
          workspace: project-dir