apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-run
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/iocanel/quarkus-helloworld
  workspaces:
    - name: project-dir
      persistentVolumeClaim:
        claimName: project-pvc
