apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- m2-repo-pvc.yaml
- project-pvc.yaml

patches:
- patch: |
    - op: replace #action
      path: /spec/storageClassName #resource we want to change
      value: standard #value we want to use for patching
  target:
    version: v1
    kind: PersistentVolumeClaim