kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: project-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-csi
  volumeMode: Filesystem
